### ISSUE TITLE
How denormalize avoiding MixedRelations error?

### ISSUE THREAD

**Issue by Vrael** [mongoid/mongoid#3949] opened 2015-02-15 19:14 UTC
Mongoid doesn't accept to reference an embedded document so I'm trying to think in ways to denormalizing my data for reaching the same functionality but avoiding this error.

Example:
```ruby
Class User
  include Mongoid::Document
  has_many :comments
end

Class Places
  include Mongoid::Document
  embeds_many :comments
end

class Comment
  include Mongoid::Document
  embedded_in :places
  belongs_to :user
end
```
This triggers the error: Mongoid::Errors::MixedRelations
So my goal is to be able to ask: 
(From an User) What are the comments belongs to that user?
(From a Comment) Who is the user who wrote the comment?

My doubts:
Is it a good practices duplicating the comments?

```ruby
class Comment
  include Mongoid::Document
  embedded_in :user
  embedded_in :places
  belongs_to :user
end
```
+ Pros: Avoid the reference (faster)
- Cons: 
  1. Save comments (in Place and User at the same time)
  2. There could be an inconsistency between comments in Place and in User if one of the collections were modified without modifying the other.

Is it a better solution integrating everything into a unique collection?
```ruby
Class User
  include Mongoid::Document
  embeds_many :places
end
```
+ Pros: Avoid the reference (faster)
- Cons: 
  1. Redundancy (place & comments are repeated in every user who did a comment)
  2. Users and Places are not really related between them (we are forcing the relationship)

Other alternative?
What schemes do you use for sceneries like this?

**Comment by arthurnn** [comment] 2015-02-15 19:51
I would say the duplicate of comments is a OK solution.
As this is not a Mongoid issue, I would try to ask this on stackoverflow.com , as you might find more answers there.

thanks

**Closed by arthurnn** 2015-02-15 19:51 UTC
