### ISSUE TITLE
Dup/clone of a document that has old fields causes an error unless you include Mongoid::Attributes::Dynamic

### ISSUE THREAD

**Issue by jonhyman** [mongoid/mongoid#4030] opened 2015-04-08 18:36 UTC
One of the greatest things about MongoDB is the flexible schema. If you have a model that has some fields and you later decide to remove those fields without doing a migration and `$unset`'ing them from the documents, you will get an error if you later `dup` or `clone` the document:

```ruby
class Foo
  include Mongoid::Document
  field :name, :type => String
end

f = Foo.create
Foo.collection.find({:_id => f.id}).update(:$set => {:old_property => "value"})
f.reload()
f.dup

Mongoid::Errors::UnknownAttribute:
Problem:
  Attempted to set a value for 'old_property' which is not allowed on the model Foo.
Summary:
  Without including Mongoid::Attributes::Dynamic in your model and the attribute does not already exist in the attributes hash, attempting to call Foo#old_property= for it is not allowed. This is also triggered by passing the attribute to any method that accepts an attributes hash, and is raised instead of getting a NoMethodError.
Resolution:
  You can include Mongoid::Attributes::Dynamic if you expect to be writing values for undefined fields often.
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/attributes/processing.rb:100:in `process_attribute'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/attributes/processing.rb:25:in `block in process_attributes'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/attributes/processing.rb:23:in `each_pair'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/attributes/processing.rb:23:in `process_attributes'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/document.rb:110:in `block in initialize'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/threaded/lifecycle.rb:84:in `_building'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/document.rb:104:in `initialize'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/copyable.rb:25:in `new'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/bundler/gems/mongoid-4294ce79f6aa/lib/mongoid/copyable.rb:25:in `clone'
	from (irb):23
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/jonathan/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'2.1.5 :024 >
```

**Comment by muichkine** [comment] 2015-04-09 08:16
The error makes sesne, You need to include the Mongoid::Attributes::Dynamic module in order to use data not covered by `fields`.

**Comment by jonhyman** [comment] 2015-04-09 08:30
I understand why the error is being thrown. But I think that in any
reasonably long development project at some point you're going to change
schemas and perhaps remove a field from some model. And mongodb's flexible
schemas means that you don't strictly need to $unset anything.

That you can then pull back the model which has an old field on it from the
db just fine but dup fails is, to me, a troublesome point because it means
that if at any point you ever remove a field from a model but don't $unset
that field you should add the Dynamic attribute mixin to your module or you
could find that your code to dup suddenly fails with old database documents
(new ones would work just fine, and probably all your unit tests that cover
your code which uses dup will work just fine, but perhaps you'll run into
this error in prod and get frustrated because it'll force you to either
$unset or include Dynamic). I just think that long term, models change, so
the trend is going to be that all models will include Dynamic.

For us we're probably going to add Dynamic to all our main models. We've
been developing for 3 years on mongodb and have absolutely removed fields
in that time.

I hope that context makes more sense as to why I think this is a bug. I get
why the error would be raised if you try to set a field that doesn't exist
but dup seems different to me. If you have a document you can pull back
from the db without it errroring, you should be able to dup it safely. I
would never expect dup to raise an error.

**Comment by muichkine** [comment] 2015-04-09 14:50
Hello @jonhyman, what you say makes perfect sense. If one wants to leave unused/garbage in a mongodb and be fine with it, there is no reason to stop anyone from doing that.

For such developement process, just including DynamicAttributes to the model is an easy enough process to get the desired behavior.

One could also write a mongoid_migration (https://github.com/adacosta/mongoid_rails_migrations) since they are really easy to unset everything.

Now, for the dup/clone behavior. I don't think that doing a reload goes back to the database checking all the attributes. I think it just reloads the fields it knows. That would explain the behavior you see in your example. Now, one real trouble I think, which I reported recently is that clone/dup a mongoid model, and the new model queries everything from the db instead of pulling them from the model it was cloned from. 

That's not a bug, but that could be improved I think.

**Comment by jonhyman** [comment] 2015-04-09 15:56
@muichkine, the old attributes are pulled from the database just fine, which is why `dup` failing is so problematic. I don't think that this code should raise an exception, it causes a minefield for debugging. And yes, while include `Dynamic::Attributes` is a workaround, I'm saying that I think that by and large, if you have models which have been around for a long time, you're going to want to put `Dynamic::Attributes` on all of them if this problem persists because the risk of a `dup` raising an exception when it touches a document with a legacy field can be bad for your application, and it's not intuitive.

```ruby
class Foo
  include Mongoid::Document
  field :name, :type => String
end

f = Foo.create
Foo.collection.find({:_id => f.id}).update(:$set => {:old_property => "value"})
f2 = Foo.find(f.id)
f2.as_document
# => {"_id"=>BSON::ObjectId('55269fd86a6f6e6c9c010000'), "old_property"=>"value"}
f2.dup
# => raises Mongoid::Errors::UnknownAttribute:
```

As for the gem you suggest, those kinds of migrations don't work in MongoDB at scale. Multiple collections of ours have millions, tens of millions, and even hundreds of millions of documents. Any kind of bulk updating locks the database and will cause a massive service interruption. All migrations that we do involve slowly iterating across collections to do single updates across shards and pausing at intervals to keep lock % down and minimize impact on the cluster. Migrations on large collections can take days, so many times we just choose to let existing data sit.

I definitely think that any situation in which a `dup` will raise an exception is a bug.

**Comment by huanzhang** [comment] 2015-05-06 07:09
@jonhyman will 5.0.0 fix this?

**Comment by jonhyman** [comment] 2015-05-06 12:44
It's in the milestone. As to whether or not it'll actually get fixed, I can't say.

**Comment by durran** [comment] 2015-05-08 16:51
This will be in 5.0.0.

**Closed** 2015-06-05 17:42 UTC
