### ISSUE TITLE
BSON::Document, Rails 4.2.0 and symbolize_keys issue

### ISSUE THREAD

**Issue by Intrepidd** [mongoid/mongoid#3904] opened 2014-12-31 16:49 UTC
Not sure if this belongs here.

With active support 4.2.0 :

```ruby
BSON::Document.new('hello' => 'world').symbolize_keys
=> {"hello"=>"world"}
```

This is because as of 4.2.0, ``symbolize_keys`` does not return a Hash all the time, but an instance of the object : 

```ruby
def transform_keys
  return enum_for(:transform_keys) unless block_given?
  result = self.class.new
  each_key do |key|
    result[yield(key)] = self[key]
  end
  result
end
```

What could be done here ?
- Is this Active Support's problem ?
- should bson reimplement this method ?
- should bson delegate this method to ``to_h`` ?

Thanks

**Comment by alex-shapiro** [comment] 2015-01-14 19:55
+1 This is causing `rake db:mongoid:remove_undefined_indexes` to remove indexes that *are* defined.

**Comment by NaixSpirit** [comment] 2015-02-10 08:40
+1 `rake db:mongoid:remove_undefined_indexes` removed all indexes which are defined :sob:

**Comment by arthurnn** [comment] 2015-02-14 18:37
Is this a ActiveModel 4.2.0 thing?
Indeed our tests are not green with latest rails stable (4.2.x).
We need to solve that.. thanks

**Comment by arthurnn** [comment] 2015-02-14 18:44
So I guess this is a problem with mongoid + rails 4.2 , because of https://github.com/rails/rails/pull/16149 . I will investigate what is the best fix.. thanks

**Comment by arthurnn** [comment] 2015-02-14 22:43
Should be fixed by https://github.com/mongoid/mongoid/commit/27623b231b5f58b987025c590f7111cac751bff3

thanks all

**Closed by arthurnn** 2015-02-14 22:43 UTC

**Comment by Intrepidd** [comment] 2015-02-14 22:49
Correct me if I'm wrong but it seems that you fixed the issue in the rake
task, but that does not address the initial issue. Other pieces of code
might break. But this may not be mongoid's Job to fix it.

**Comment by Intrepidd** [comment] 2015-02-14 23:06
IMO, the best way to get rid of this would be to delegate ``symbolize_keys`` to ``to_h`` in mongoid/bson-ruby

**Comment by arthurnn** [comment] 2015-02-14 23:12
@Intrepidd right, see my other fix https://github.com/mongoid/mongoid/commit/317aa53ab8f6a678f4506a92b64838b463d05786

**Comment by Intrepidd** [comment] 2015-02-14 23:15
My bad, I did not see this commit.

This is perfect then ! Thanks for fixing this ! :beers:

**Comment by Intrepidd** [comment] 2015-02-14 23:16
Heh, but in this case, is 27623b23 really relevant ? Test should still pass if you revert it right ?

**Comment by arthurnn** [comment] 2015-02-14 23:40
@Intrepidd yep, I am adding regression tests, and fixing that code. :heart:
