### ISSUE TITLE
Saving embedded grandchildren creates additional embedded documents

### ISSUE THREAD

**Issue by adamcrown** [mongoid/mongoid#4033] opened 2015-04-10 18:43 UTC
I ran into an issue where I have a model that `embeds_many` of another model, that has it's own `embeds_many`.

For example:
```yaml
parent:
  - child_1:
  - child_2:
    - grandchild
```

The issue comes up when you update one of the grandchildren. It saves the grandchild just fine but also creates a additional grandchild record. The number of records that get created is directly tied to how many children there are. Three children will create three grandchild records. If there is only one child record, there is no problem.

I created a repo with specs do demonstrate this: https://github.com/adamcrown/grandchild-save-bug

The best workaround I've found is to call save on the child instead of the grandchild.

_For some reason I can't get Travis CI to reproduce the bug, but I've reproduced it on multiple computers. Please clone the repo and let me know if it passes for you. There should be one failed and one passed spec._

**Comment by mikestephens** [comment] 2015-04-10 22:44
+1 I experience the same issue

**Comment by muichkine** [comment] 2015-04-14 08:07
Could be a duplicate of https://github.com/mongoid/mongoid/issues/3532 ?

**Comment by cenotaph** [comment] 2015-04-25 11:29
+1 for me. This also ignores validations and created empty records that can't be deleted through mongoid. Maybe I am just using update wrong in my controller??

**Comment by durran** [comment] 2015-06-17 08:15
This is an issue with MongoDB's positional operator `$` from 2.6 and higher. (Which is why on travis this is not reproducable - they are still on MongoDB 2.4). I'm removing Mongoid's use of this operator and using only pure indexes now.

**Closed** 2015-06-17 08:24 UTC
